### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by evansiroky**
First tests for mastarm!  Includes coverage reporting to codecov.

### CODE REVIEW

**Comment by trevorgerhardt** [comment]
Does Jest come with it's own assertion library? I'm wondering if Chai is a necessary dependency. All of the examples I've seen with Jest tend to "assume" that the `expect` function exist without installing anything explicitly other than Jest.

**Comment by evansiroky** [comment]
Yes, Jest has it's own expect assertion library, but it's kind of limited.  The main thing that I liked about chai was the type assertion, but I guess I could implement that with Jest's expect assertions.

**Comment by trevorgerhardt** [comment]
@evansiroky I figure if we buy into Jest, we should at least start with their assertion library as the "default" and then possibly switch to Chai in certain test environments where we need it.

**Comment by evansiroky** [comment]
Did you do a `npm prune` after removing chai?  The `should` api should not work unless chai is installed.  I removed the dependency.

**Pull request merged**
