### PR TITLE
Merge latest Jest changes into master to create a new version

### PR DESCRIPTION
**Pull request by evansiroky**

### CODE REVIEW

**Comment by evansiroky** [comment]
The test for `mastarm build` has been acting flaky.  One of these CI runs failed but then passed when I restarted it.

**Comment by trevorgerhardt** [comment]
Are these changes needed for a specific purpose? One of the major reasons why I wanted to split out dev from master is to group feature/fixes for less releases.

**Comment by trevorgerhardt** [comment]
By "specific purpose" I meant, is this stopping you from working on another task until it gets through?

**Comment by evansiroky** [comment]
It's not stopping me from completing other tasks.  Although the Jest pattern matching is definitely a nice feature to have right away.

**Pull request merged**
