### PR TITLE
v2.1.0

### PR DESCRIPTION
**Pull request by trevorgerhardt**

### CODE REVIEW

**Comment by trevorgerhardt** [comment]
@evansiroky I'm not sure what I did here but it appears that this PR contains commits that already made it into master. 🤔

**Comment by evansiroky** [comment]
Not sure what happened either.  Maybe we'll get a long list of stuff each time since we're rebasing?

**Comment by trevorgerhardt** [comment]
@evansiroky if that's the case should we just use merge commits on PRs? The list of commits will become extremely long and useless.

**Comment by evansiroky** [comment]
Yeah, if it is the case, merging would be better, but I don't know if it is the case.

**Pull request merged**
