### PR TITLE
Allow passthrough of any jest CLI arguments

### PR DESCRIPTION
**Pull request by evansiroky**
This change allows for the output of a test run to a specified json file.

### CODE REVIEW

**Comment by evansiroky** [comment]
@landonreed, any chance this can get included in #270?

**Comment by landonreed** [comment]
Oh, sorry @evansiroky. I didn't see this until now. Any reason we don't just allow any option to pass through to jest?

**Comment by evansiroky** [comment]
Ok, I removed the json report thingy and made a different option to pass through any option to the Jest cli.

**Pull request merged**
